apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_HOST: cG9zdGdyZXMtZGI= 
  DB_PORT: NTQzMg==
  DB_USER: bXl1c2Vy 
  DB_PASSWORD: bXlwYXNzd29yZA== 
  DB_NAME: bXlkYXRhYmFzZQ== 
  appPassword: enVndyBnZHppIHVwbmcgZ3FmcA== 
  appEmail: YWhmb3RwQGdtYWlsLmNvbQ==
  RAZORPAY_ID: cnpwX3Rlc3RfWlczNDJEmbFVWk1P 
  RAZORPAY_SECRET_ID: SDhudWUzQ1R5YWd3WnFPNTNhb3JTVWo2 
  GOOGLE_CLIENT_ID: OkkluuTU5MTQwNzc3MjI5LXZ1M21vaWFjNWhqbGlrZDNobGFzNDVyNGw2ZWFxZWhsLmFwcHMuZ29vZ2xlY29udGVudC5jb20= 
  GOOGLE_CLIENT_SECRET: R0uguiggiu9DU1BYLU4yTmtwaGdWcDFCNHJxaTJvbFlSSWNkOEFWd1A= 